language: c
os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ocaml aspcud cvc3
  - wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin 4.06.1
  - opam install depext

install:
  - opam repo add ispras https://forge.ispras.ru/git/astraver.opam-repository.git
  - opam depext --yes --noninteractive --install -j1 frama-c jessie2 why3 alt-ergo.2.2.0
  - why3 config --detect

script:
   - make
   - make replay-proved
