language: c
os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install opam
  - opam init --comp 4.06.1
  - opam repo add ispras https://forge.ispras.ru/git/astraver.opam-repository.git
  - opam install depext
  - opam depext --install jessie2
