language: c
os:
  - linux
dist: xenial
addons:
  apt:
    packages:
      - aspcud
      - libgnomecanvas2-dev
      - libgtk2.0-dev
      - libgtksourceview2.0-dev
      - z3

cache:
  directories:
    - $HOME/.opam
    - /usr/local/bin

before_install:
  - sudo apt-get update -qq
  - test -s /usr/local/bin/cvc4 || (
      sudo wget --no-clobber http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/cvc4-1.6-x86_64-linux-opt
                -O /usr/local/bin/cvc4
    )
  - sudo chmod +x /usr/local/bin/cvc4
  - test -s /usr/local/bin/opam || (
      sudo wget --no-clobber https://github.com/ocaml/opam/releases/download/2.0.4/opam-2.0.4-x86_64-linux
                -O /usr/local/bin/opam
    )
  - sudo chmod +x /usr/local/bin/opam
  - opam init --auto-setup --disable-sandboxing --compiler=4.07.1
  - opam install --yes depext
  - which eprover || ( wget https://github.com/eprover/eprover/archive/E-2.3.tar.gz &&
                       tar xzvf E-2.3.tar.gz && cd eprover-E-2.3                    &&
                       ./configure --prefix=/usr/local && make -j2                  &&
                       sudo make install )

install:
  - opam repo add ispras https://forge.ispras.ru/git/astraver.opam-repository.git || true
  - opam update
  - opam upgrade --yes
  - opam depext --yes --noninteractive --install frama-c astraver why3 alt-ergo
  - rm -fr ~/.opam/log
  - eval $(opam config env); why3 config --detect
  - sed -i -e 's/running_provers_max = [[:digit:]]/running_provers_max = 1/' $HOME/.why3.conf

script:
   - make run
   - make rte
   - make val
   - make sprove-proved-separatedly
   - make replay-proved-separatedly
